# Generated by Django 4.2.7 on 2025-06-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_host_location_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pdriving_license',
            new_name='driving_license',
        ),
    ]
