# Generated by Django 4.2.7 on 2025-06-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rename_pdriving_license_user_driving_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('CNG', 'CNG'), ('None', 'None')], default='petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi_Automatic', 'Semi_Automatic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4_Wheeler', '4_Wheeler'), ('2_Wheeler', '2_Wheeler'), ('Bicycle', 'Bicycle')], max_length=20),
        ),
    ]
