# Generated by Django 4.2.7 on 2025-06-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('mpv', 'MPV'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('van', 'Van'), ('bicycle', 'Bicycle')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Additional features of the vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default=1, help_text='Vehicle license plate number', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric'), ('hybrid', 'hybrid'), ('cng', 'cng'), ('none', 'none')], default='petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('manual', 'manual'), ('automatic', 'automatic'), ('cvt', 'cvt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4_wheeler', '4_wheeler'), ('2_wheeler', '2_wheeler'), ('bicycle', 'bicycle')], max_length=20),
        ),
    ]
