# Generated by Django 4.2.7 on 2025-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_vehicle_category_vehicle_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('MUV', 'MUV'), ('Luxury', 'Luxury'), ('Sports', 'Sports'), ('Other', 'Other'), ('Bicycle', 'Bicycle')], default='sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4_wheeler', '4_wheeler'), ('2_wheeler', '2_wheeler'), ('Bicycle', 'Bicycle'), ('Other', 'Other')], max_length=20),
        ),
    ]
