# Generated by Django 4.2.7 on 2025-06-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_vehicle_category_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
    ]
