# Generated by Django 4.2.7 on 2025-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20, null=True),
        ),
    ]
